Repository young-02/BeMyDesk, pull requests merged in 2023-03, with the labels that each got.

#73 img 태그 -> Image 태그 수정
  components/GlobalNavigationBar.tsx
  components/detail-write/DetailWriteForm.tsx
  components/detail-write/DetailWriteProductCard.tsx
  components/detail-write/DetailWriteSearch.tsx
  components/detail/DetailViewProducts.tsx
  components/detail/DetailViewSlide.tsx
  components/detail/DetailViewUserInfor.tsx
  components/mypage/ProfileEditModal.tsx
  components/mypage/contents/MyFollow.tsx
  components/mypage/contents/MyPost.tsx
  components/mypage/contents/MyScrap.tsx
  components/post-list/PostListItem.tsx
  next.config.js
  pages/auth/sign-in/index.tsx
  pages/mypage/index.tsx
Labels: bug

#74 vercel 배포에러 수정
  package.json
Labels: bug

#81 글쓰기 페이지 UI 수정
  components/detail-write/DetailWriteForm.tsx
  components/detail-write/DetailWriteFormEditor.tsx
  components/detail-write/DetailWriteProductCard.tsx
  components/detail-write/DetailWriteSearch.tsx
  components/detail-write/DetailWriteSearchModal.tsx
  public/images/Search.png
Labels: enhancement

#85 naverData get 요청 url 수정, data 이름 변경
  components/detail-write/DetailWriteForm.tsx
  components/detail-write/DetailWriteProductCard.tsx
  components/detail/DetailViewProducts.tsx
Labels: enhancement

#86 ✨: 회원가입, SNS회원가입, 프로필 수정 닉네임 중복검사 구현 #31 #35
  components/mypage/editProfile/ChangeProfile.tsx
  next.config.js
  pages/auth/sign-in/index.tsx
  pages/auth/sign-up/index.tsx
  pages/auth/sns-nickname/index.tsx
Labels: enhancement

#87 Feat/mypage 회원탈퇴 추가
  components/mypage/ProfileEditModal.tsx
  components/mypage/editProfile/ChangeProfile.tsx
  components/mypage/editProfile/DeleteAccount.tsx
  pages/auth/sign-in/index.tsx
Labels: enhancement

#88 비밀번호 찾기페이지 CSS작업, 전체페이지 버튼 호버넣기
  components/mypage/CategoryButton.tsx
  components/mypage/ProfileEditModal.tsx
  components/mypage/editProfile/ChangePassword.tsx
  components/mypage/editProfile/ChangeProfile.tsx
  components/mypage/editProfile/DeleteAccount.tsx
  pages/auth/find-password/index.tsx
  pages/auth/sign-in/index.tsx
  pages/auth/sign-up/index.tsx
  pages/auth/sns-nickname/index.tsx
  pages/mypage/index.tsx
Labels: enhancement

#92 mypage bug fix
  components/mypage/ProfileEditModal.tsx
  components/mypage/editProfile/ChangePassword.tsx
  components/mypage/editProfile/ChangeProfile.tsx
  pages/auth/find-password/index.tsx
  pages/auth/sns-nickname/index.tsx
  pages/mypage/index.tsx
Labels: bug

#93 회원가입시 데이터 구조 변경, 비밀번호 찾기시 소셜로그인 유저 검증
  pages/auth/find-password/index.tsx
  pages/auth/sign-up/index.tsx
  pages/auth/sns-nickname/index.tsx
Labels: enhancement

#95 글쓰기 페이지 UI 수정, 이미지 미리보기 및 이미지 다중 업로드 기능 추가(WIP)
  components/detail-write/DetailWriteForm.tsx
  components/detail-write/DetailWriteProductCard.tsx
  components/detail-write/DetailWriteSearch.tsx
  components/detail/DetailView.tsx
  components/detail/DetailViewSlide.tsx
  components/ui/CustomButton.tsx
  pages/detail/write/[id]/edit.tsx
  pages/detail/write/index.tsx
Labels: enhancement

#97 이미지 압축 라이브러리 적용, 파이어베이스 이미지 업로드 시 url이 잘못 들어가는 부분 수정 완료
  components/detail-write/DetailWriteForm.tsx
  pages/detail/write/index.tsx
Labels: enhancement

#98 중복되는 코드 삭제, 포스트 카드, 스크랩 카드에 정규식 적용
  components/detail-write/DetailWriteForm.tsx
  components/detail/DetailView.tsx
  components/mypage/contents/PostCard.tsx
  components/mypage/contents/ScrapCard.tsx
Labels: enhancement

#99 💄 Design: auth 페이지 전반적인 CSS 수정
  pages/auth/find-password/index.tsx
  pages/auth/sign-in/index.tsx
  pages/auth/sign-up/index.tsx
  pages/auth/sns-nickname/index.tsx
  pages/mypage/index.tsx
Labels: enhancement

#101 ✨ Feat: 회원가입시 환영 모달 추가 #31
  components/mypage/editProfile/ChangeProfile.tsx
  components/post-list/SignUpModal.tsx
  package.json
  pages/auth/sign-up/index.tsx
  pages/auth/sns-nickname/index.tsx
  pages/mypage/index.tsx
  pages/post-list/index.tsx
Labels: enhancement

#103 🚑 !HOTFIX: removeQueries를 invalidateQueries로 변경, 변경완료시 모달닫기 주석처리(임시) #35
  components/mypage/editProfile/ChangeProfile.tsx
Labels: bug

#106 auth 페이지용 커스텀 UI 추가, 마이페이지 물음표 해상도 변경 #30 #31 #32 #37
  components/mypage/contents/MyFollow.tsx
  components/mypage/contents/MyPost.tsx
  components/mypage/contents/MyScrap.tsx
  components/ui/authUi/CustomAuthUI.tsx
  components/ui/authUi/CustomErrorMessage.tsx
  components/ui/authUi/CustomInput.tsx
Labels: enhancement

#110 🔨 Fix: 회원가입 모달 오류 수정#31
  components/post-list/SignUpModal.tsx
  pages/auth/sns-nickname/index.tsx
  pages/post-list/index.tsx
Labels: bug

#114 ✨ Feat : 회원가입, sns회원가입 재사용 UI 컴포넌트로 리팩토링, mypage 자기소개 요소 수정 #31 #35
  components/Footer.tsx
  components/mypage/ProfileEditModal.tsx
  components/post-list/SignUpModal.tsx
  components/ui/CustomButton.tsx
  components/ui/authUi/CustomAuthUI.tsx
  components/ui/authUi/CustomErrorMessage.tsx
  components/ui/authUi/CustomInput.tsx
  pages/auth/find-password/index.tsx
  pages/auth/sign-in/index.tsx
  pages/auth/sign-up/index.tsx
  pages/auth/sns-nickname/index.tsx
  pages/mypage/index.tsx
  public/images/workingDesk.png
Labels: enhancement

#120 UI/mypage
  components/mypage/contents/DeleteModal.tsx
  components/mypage/contents/PostCard.tsx
  pages/auth/sign-up/index.tsx
  pages/mypage/index.tsx
Labels: enhancement

#122 모바일 반응형 추가(WIP)
  components/detail-write/DetailWriteForm.tsx
  components/detail-write/DetailWriteProductCard.tsx
  components/detail-write/DetailWriteSearch.tsx
  components/detail-write/DetailWriteSearchModal.tsx
  pages/index.tsx
  public/favicon.ico
  styles/globals.css
Labels: documentation

#125 UI/mypage
  components/mypage/CategoryButton.tsx
  components/mypage/ProfileEditModal.tsx
  components/mypage/contents/FollowingCard.tsx
  components/mypage/contents/MyFollow.tsx
  components/mypage/contents/MyPost.tsx
  components/mypage/contents/MyScrap.tsx
  components/mypage/contents/PostCard.tsx
  components/mypage/contents/ScrapCard.tsx
  components/mypage/editProfile/ChangePassword.tsx
  components/mypage/editProfile/ChangeProfile.tsx
  components/mypage/editProfile/DeleteAccount.tsx
  pages/mypage/index.tsx
Labels: enhancement

#128 Feat/edit
  components/detail-write/DetailWriteForm.tsx
  components/detail-write/DetailWriteProductCard.tsx
  components/detail-write/DetailWriteSearch.tsx
Labels: documentation

#130 검색 모달 오버레이 크기 변경, api url 변경, 카테고리 추가
  components/detail-write/DetailWriteForm.tsx
  components/detail-write/DetailWriteSearch.tsx
  components/detail-write/DetailWriteSearchModal.tsx
Labels: bug

#133 글쓰기 페이지 이미지 업로드 문구 수정
  components/detail-write/DetailWriteForm.tsx
Labels: enhancement

#138 UI/mypage
  components/mypage/ProfileEditModal.tsx
  components/mypage/editProfile/ChangePassword.tsx
  components/mypage/editProfile/ChangeProfile.tsx
  components/mypage/editProfile/DeleteAccount.tsx
  pages/auth/sign-in/index.tsx
  pages/auth/sign-up/index.tsx
Labels: enhancement

#142 update README.md
  README.md
Labels: enhancement

#143 :hammer:Fix : 회원탈퇴 회원인증 방식변경
  components/mypage/editProfile/DeleteAccount.tsx
  components/ui/authUi/CustomAuthUI.tsx
  pages/auth/sns-nickname/index.tsx
Labels: enhancement
